# Datasetbeschrijving 

Voor dit onderzoek is gebruikgemaakt van twee datasets.

## Los Angeles

Voor dit onderzoek is gebruikgemaakt van de dataset **"Crime Data from 2020 to 2024"**, beschikbaar gesteld door de Los Angeles Police Department (LAPD). De dataset bevat informatie over geregistreerde misdrijven in de stad Los Angeles tussen 2020 en 2024. Elke rij vertegenwoordigt één geregistreerd misdrijf. De dataset bevat ongeveer **1 miljoen observaties (rijen)** en **28 variabelen (kolommen)**.

### Variabelen in de dataset

#### 1. Identificatie van het misdrijf

Deze variabelen identificeren een specifiek politieverslag:

- **dr_no**: uniek dossiernummer van het misdrijf.
- **part_1_2**: classificatie van het misdrijf volgens de FBI-indeling (*Part I* of *Part II*).

#### 2. Tijdsgegevens

Deze variabelen beschrijven wanneer het misdrijf plaatsvond en wanneer het werd gemeld:

- **date_rptd**: datum waarop het misdrijf werd gemeld.
- **date_occ**: datum waarop het misdrijf plaatsvond.
- **time_occ**: tijdstip waarop het misdrijf plaatsvond.

#### 3. Locatiegegevens

Deze variabelen beschrijven waar het misdrijf plaatsvond:

- **area**: nummer van het LAPD-politiegebied.
- **area_name**: naam van het politiegebied.
- **rpt_dist_no**: rapportagedistrict binnen het politiegebied.
- **location**: afgerond adres van het incident.
- **cross_street**: dichtstbijzijnde kruising.
- **lat**: breedtegraad van de locatie.
- **lon**: lengtegraad van de locatie.

#### 4. Misdrijfkenmerken

Deze variabelen beschrijven het gepleegde misdrijf:

- **crm_cd**: code van het misdrijf.
- **crm_cd_desc**: beschrijving van het misdrijf.
- **crm_cd_1**: primaire misdrijfcode.
- **crm_cd_2**, **crm_cd_3**, **crm_cd_4**: eventuele aanvullende misdrijfcodes.
- **mocodes**: modus-operandi-codes die aangeven hoe het misdrijf werd gepleegd.

#### 5. Slachtofferkenmerken

Deze variabelen beschrijven kenmerken van het slachtoffer:

- **vict_age**: leeftijd van het slachtoffer.
- **vict_sex**: geslacht van het slachtoffer.
- **vict_descent**: etnische of culturele achtergrond van het slachtoffer.

#### 6. Overige incidentkenmerken

Deze variabelen geven aanvullende informatie over het incident:

- **premis_cd** en **premis_desc**: type locatie waar het misdrijf plaatsvond.
- **weapon_used_cd** en **weapon_desc**: informatie over een eventueel gebruikt wapen.
- **status** en **status_desc**: status van de zaak.

### Geselecteerde variabelen

Niet alle variabelen zijn relevant voor het onderzoek. Daarom is een selectie gemaakt van de variabelen die het beste aansluiten bij het analyseren van verschillen in criminaliteit tussen gebieden en slachtofferprofielen.

| Variabele | Doel |
|------------|------|
| `date_occ` | Bepalen wanneer een misdrijf plaatsvond |
| `crm_cd_desc` | Het type misdrijf analyseren |
| `part_1_2` | Onderscheid maken tussen ernstigere en minder ernstige misdrijven |
| `area_name` | Criminaliteit tussen verschillende politiegebieden vergelijken |
| `vict_age` | Leeftijdsverschillen tussen slachtoffers onderzoeken |
| `vict_sex` | Verschillen tussen mannelijke en vrouwelijke slachtoffers analyseren |
| `vict_descent` | Verschillen in slachtofferachtergrond onderzoeken |
| `lat`, `lon` | Geografische spreiding van misdrijven visualiseren en hotspots identificeren |

Deze variabelen bevatten samen informatie over wanneer een misdrijf plaatsvond, waar het plaatsvond, welk type misdrijf het betrof en wie het slachtoffer was. Hierdoor vormen ze een goede basis voor het beantwoorden van de onderzoeksvraag.

### Afgeleide variabelen

Naast de oorspronkelijke variabelen zijn twee nieuwe variabelen aangemaakt op basis van `date_occ`:

- **year**: het jaar waarin het misdrijf plaatsvond.
- **month**: de maand waarin het misdrijf plaatsvond.

Deze afgeleide variabelen maken het mogelijk om trends en patronen in criminaliteit over verschillende jaren en maanden te onderzoeken.

---

## New York

Voor dit onderzoek is gebruikgemaakt van de dataset "NYPD Arrests Data (Historic)", beschikbaar gesteld door de New York City Police Department (NYPD). De dataset bevat informatie over arrestaties die zijn verricht door de politie in New York City. Elke rij in de dataset vertegenwoordigt één arrestatie. De dataset bevat ongeveer 6,26 miljoen observaties (rijen) en 19 variabelen (kolommen).

### Variabelen in de dataset

#### 1. Tijdsgegevens

Deze variabelen beschrijven wanneer de arrestatie plaatsvond:

- **arrest_date**: exacte datum van de arrestatie.

#### 2. Delict- en juridische kenmerken

Deze variabelen beschrijven het delict waarvoor iemand is gearresteerd:

- **pd_cd**: gedetailleerde interne classificatiecode van het delict.
- **pd_desc**: beschrijving van de PD-code.
- **ky_cd**: algemene classificatiecode van het delict.
- **ofns_desc**: beschrijving van het type overtreding of misdrijf.
- **law_code**: verwijzing naar de relevante wetgeving.
- **law_cat_cd**: ernstcategorie van het delict (*felony*, *misdemeanor* of *violation*).

#### 3. Locatiegegevens

Deze variabelen beschrijven waar de arrestatie plaatsvond:

- **arrest_boro**: stadsdeel waarin de arrestatie plaatsvond (*Bronx, Brooklyn, Manhattan, Queens* of *Staten Island*).
- **arrest_precinct**: politiedistrict waarin de arrestatie plaatsvond.
- **jurisdiction_code**: instantie die verantwoordelijk was voor de arrestatie.
- **x_coord_cd**: X-coördinaat binnen het New York State Plane Coordinate System.
- **y_coord_cd**: Y-coördinaat binnen het New York State Plane Coordinate System.
- **latitude**: breedtegraad.
- **longitude**: lengtegraad.
- **lon_lat**: gecombineerd geografisch punt op basis van latitude en longitude.

#### 4. Kenmerken van de verdachte

Deze variabelen beschrijven de persoon die is gearresteerd:

- **age_group**: leeftijdscategorie van de verdachte.
- **perp_sex**: geslacht van de verdachte.
- **perp_race**: etnische of raciale achtergrond van de verdachte.

### Geselecteerde variabelen

Voor deze analyse is een selectie gemaakt van de variabelen die relevant zijn voor het onderzoeken van verschillen tussen de stadsdelen van New York en de kenmerken van arrestaties.

| Variabele | Doel |
|------------|------|
| `arrest_date` | Bepalen wanneer een arrestatie plaatsvond |
| `ofns_desc` | Het type overtreding of misdrijf analyseren |
| `law_cat_cd` | Onderscheid maken tussen overtredingen, misdrijven en ernstige misdrijven |
| `arrest_boro` | Arrestaties tussen de verschillende stadsdelen vergelijken |
| `age_group` | Leeftijdsverschillen tussen verdachten onderzoeken |
| `perp_sex` | Verschillen tussen mannelijke en vrouwelijke verdachten analyseren |
| `perp_race` | Verschillen in achtergrond van verdachten onderzoeken |
| `latitude`, `longitude` | Geografische spreiding van arrestaties in kaart brengen |

Deze variabelen geven gezamenlijk inzicht in wanneer een arrestatie plaatsvond, waar deze plaatsvond, waarvoor iemand werd gearresteerd en welke kenmerken de verdachte had.

### Afgeleide variabelen

Naast de oorspronkelijke variabelen zijn twee nieuwe variabelen aangemaakt op basis van `arrest_date`:

- **year**: het jaar waarin de arrestatie plaatsvond.
- **month**: de maand waarin de arrestatie plaatsvond.

Deze afgeleide variabelen maken het mogelijk om arrestaties over de tijd te analyseren en trends tussen verschillende jaren en maanden te onderzoeken. Hierdoor kan bijvoorbeeld worden bekeken of bepaalde typen misdrijven vaker voorkomen in specifieke perioden of hoe arrestatiepatronen zich in de loop der jaren hebben ontwikkeld.

# Data voorverwerking

In [ ]:
import pandas as pd
import os

# Inladen van datasets

## Dataset Los Angeles

In [ ]:
# If file is not downloaded, get directly from source
if not os.path.isfile("../data/raw/crime_la.csv"):
    df_lapd = pd.read_csv("https://data.lacity.org/resource/2nrs-mtv8.csv?$limit=999999999")
    df_lapd.to_csv("../data/raw/crime_la.csv")
else:
    df_lapd = pd.read_csv("../data/raw/crima_la.csv")

display(df_lapd)
print(df_lapd.columns)

## Dataset New York

In [ ]:
# If file is not downloaded, get directly from source
if not os.path.isfile("../data/raw/crime_ny.csv"):
    # Limit the dataset to entries starting from 2020
    df_nypd = pd.read_csv("https://data.cityofnewyork.us/resource/8h9b-rp9u.csv?$limit=1252000")
    df_nypd.to_csv("../data/raw/crime_ny.csv")
else:
    df_nypd = pd.read_csv("../data/raw/crime_ny.csv")

display(df_nypd)
print(df_nypd.columns)

,arrest_key,arrest_date,pd_cd,pd_desc,ky_cd,ofns_desc,law_code,law_cat_cd,arrest_boro,arrest_precinct,jurisdiction_code,age_group,perp_sex,perp_race,x_coord_cd,y_coord_cd,latitude,longitude,lon_lat
0,318190042,2025-12-31T00:00:00.000,113.0,"MENACING,UNCLASSIFIED",344.0,ASSAULT 3 & RELATED OFFENSES,PL 1201401,M,B,44,0,45-64,M,BLACK,1005903,243479,40.834952,-73.921752,POINT (-73.921752 40.834952)
1,318210353,2025-12-31T00:00:00.000,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL051101A,M,K,67,0,25-44,F,BLACK,1006762,178397,40.656307,-73.918865,POINT (-73.91886471 40.65630659)
2,318184096,2025-12-31T00:00:00.000,681.0,"CHILD, ENDANGERING WELFARE",233.0,SEX CRIMES,PL 2601001,M,M,5,0,25-44,M,WHITE HISPANIC,984990,200136,40.716012,-73.997332,POINT (-73.9973320301008 40.7160120119955)
3,318203917,2025-12-31T00:00:00.000,259.0,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",351.0,CRIMINAL MISCHIEF & RELATED OF,PL 1450001,M,B,52,0,25-44,M,BLACK,1014400,256319,40.870159,-73.890987,POINT (-73.8909872 40.8701594)
4,318204909,2025-12-31T00:00:00.000,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,M,M,1,3,25-44,M,WHITE,981073,197959,40.710038,-74.011460,POINT (-74.01146 40.710038)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1299995,202953863,2019-09-27T00:00:00.000,748.0,"CONTEMPT,CRIMINAL",359.0,OFFENSES AGAINST PUBLIC ADMINI,PL 2155006,M,M,5,0,25-44,M,BLACK,983903,200257,40.716344,-74.001253,POINT (-74.00125319299997 40.71634415200003)
1299996,202964310,2019-09-27T00:00:00.000,779.0,"PUBLIC ADMINISTRATION,UNCLASSI",126.0,MISCELLANEOUS PENAL LAW,PL 2052501,F,B,41,72,25-44,F,BLACK,1017934,232221,40.804013,-73.878332,POINT (-73.87833183299995 40.804012949000025)
1299997,202976235,2019-09-27T00:00:00.000,153.0,RAPE 3,104.0,RAPE,PL 1302503,F,B,43,0,25-44,M,WHITE HISPANIC,1020316,239179,40.823101,-73.869690,POINT (-73.86969046099995 40.82310129900003)
1299998,202969548,2019-09-27T00:00:00.000,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL05110MU,M,M,34,0,25-44,M,BLACK HISPANIC,1004993,254916,40.866344,-73.925006,POINT (-73.92500567299999 40.86634401100008)
1299999,202980168,2019-09-27T00:00:00.000,259.0,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",351.0,CRIMINAL MISCHIEF & RELATED OF,PL 1450001,M,Q,113,0,<18,M,BLACK,1050316,183451,40.669969,-73.761845,POINT (-73.76184452399997 40.669969070000036)

Index(['arrest_key', 'arrest_date', 'pd_cd', 'pd_desc', 'ky_cd', 'ofns_desc',
       'law_code', 'law_cat_cd', 'arrest_boro', 'arrest_precinct',
       'jurisdiction_code', 'age_group', 'perp_sex', 'perp_race', 'x_coord_cd',
       'y_coord_cd', 'latitude', 'longitude', 'lon_lat'],
      dtype='str')

## Datasets variabelen vergelijken

In [12]:
df_nypd.info()
df_lapd.info()

NameError: name 'df_nypd' is not defined

In [ ]:
df_nypd.columns.tolist()
df_lapd.columns.tolist()

['DR_NO',
 'Date Rptd',
 'DATE OCC',
 'TIME OCC',
 'AREA',
 'AREA NAME',
 'Rpt Dist No',
 'Part 1-2',
 'Crm Cd',
 'Crm Cd Desc',
 'Mocodes',
 'Vict Age',
 'Vict Sex',
 'Vict Descent',
 'Premis Cd',
 'Premis Desc',
 'Weapon Used Cd',
 'Weapon Desc',
 'Status',
 'Status Desc',
 'Crm Cd 1',
 'Crm Cd 2',
 'Crm Cd 3',
 'Crm Cd 4',
 'LOCATION',
 'Cross Street',
 'LAT',
 'LON']

In [ ]:
comparison = pd.DataFrame({
    "NYPD": pd.Series(df_nypd.columns),
    "LAPD": pd.Series(df_lapd.columns)
})

comparison

                 NYPD            LAPD
0          ARREST_KEY           DR_NO
1         ARREST_DATE       Date Rptd
2               PD_CD        DATE OCC
3             PD_DESC        TIME OCC
4               KY_CD            AREA
5           OFNS_DESC       AREA NAME
6            LAW_CODE     Rpt Dist No
7          LAW_CAT_CD        Part 1-2
8         ARREST_BORO          Crm Cd
9     ARREST_PRECINCT     Crm Cd Desc
10  JURISDICTION_CODE         Mocodes
11          AGE_GROUP        Vict Age
12           PERP_SEX        Vict Sex
13          PERP_RACE    Vict Descent
14         X_COORD_CD       Premis Cd
15         Y_COORD_CD     Premis Desc
16           Latitude  Weapon Used Cd
17          Longitude     Weapon Desc
18            Lon_Lat          Status
19                NaN     Status Desc
20                NaN        Crm Cd 1
21                NaN        Crm Cd 2
22                NaN        Crm Cd 3
23                NaN        Crm Cd 4
24                NaN        LOCATION
25                NaN    Cross Street
26                NaN             LAT
27                NaN             LON

# missing values bekijken

In [ ]:
missing_nypd = (
    df_nypd.isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

missing_lapd = (
    df_lapd.isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)
print(missing_nypd)
print(missing_lapd)

LAW_CAT_CD           0.718480
KY_CD                0.062483
PD_CD                0.049779
OFNS_DESC            0.011186
PD_DESC              0.011186
Lon_Lat              0.000320
Latitude             0.000320
Longitude            0.000320
ARREST_KEY           0.000000
ARREST_DATE          0.000000
LAW_CODE             0.000000
JURISDICTION_CODE    0.000000
ARREST_PRECINCT      0.000000
ARREST_BORO          0.000000
AGE_GROUP            0.000000
X_COORD_CD           0.000000
PERP_RACE            0.000000
PERP_SEX             0.000000
Y_COORD_CD           0.000000
dtype: float64
Crm Cd 4          99.993631
Crm Cd 3          99.769727
Crm Cd 2          93.118279
Cross Street      84.652312
Weapon Used Cd    67.437760
Weapon Desc       67.437760
Mocodes           15.085969
Vict Descent      14.393856
Vict Sex          14.392662
Premis Desc        0.058514
Premis Cd          0.001592
Crm Cd 1           0.001095
Status             0.000100
Vict Age           0.000000
Crm Cd             0.000000
Crm Cd Desc        0.000000
AREA NAME          0.000000
Rpt Dist No        0.000000
AREA               0.000000
TIME OCC           0.000000
Date Rptd          0.000000
DATE OCC           0.000000
DR_NO              0.000000
Part 1-2           0.000000
Status Desc        0.000000
LOCATION           0.000000
LAT                0.000000
LON                0.000000
dtype: float64

In [ ]:
threshold = 0.5

df_nypd = df_nypd.loc[:, df_nypd.isna().mean() < threshold]

In [ ]:
threshold = 0.5

df_lapd = df_lapd.loc[:, df_lapd.isna().mean() < threshold]

In [ ]:
print(df_nypd.columns.tolist())
print(df_lapd.columns.tolist())

['ARREST_KEY', 'ARREST_DATE', 'PD_CD', 'PD_DESC', 'KY_CD', 'OFNS_DESC', 'LAW_CODE', 'LAW_CAT_CD', 'ARREST_BORO', 'ARREST_PRECINCT', 'JURISDICTION_CODE', 'AGE_GROUP', 'PERP_SEX', 'PERP_RACE', 'X_COORD_CD', 'Y_COORD_CD', 'Latitude', 'Longitude', 'Lon_Lat']
['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME', 'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes', 'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc', 'Status', 'Status Desc', 'Crm Cd 1', 'LOCATION', 'LAT', 'LON']

In [ ]:
(df_nypd.isna().mean() * 100).sort_values(ascending=False)

LAW_CAT_CD           0.718480
KY_CD                0.062483
PD_CD                0.049779
OFNS_DESC            0.011186
PD_DESC              0.011186
Lon_Lat              0.000320
Latitude             0.000320
Longitude            0.000320
ARREST_KEY           0.000000
ARREST_DATE          0.000000
LAW_CODE             0.000000
JURISDICTION_CODE    0.000000
ARREST_PRECINCT      0.000000
ARREST_BORO          0.000000
AGE_GROUP            0.000000
X_COORD_CD           0.000000
PERP_RACE            0.000000
PERP_SEX             0.000000
Y_COORD_CD           0.000000
dtype: float64

In [ ]:
(df_lapd.isna().mean() * 100).sort_values(ascending=False)

Mocodes         15.085969
Vict Descent    14.393856
Vict Sex        14.392662
Premis Desc      0.058514
Premis Cd        0.001592
Crm Cd 1         0.001095
Status           0.000100
AREA             0.000000
AREA NAME        0.000000
DATE OCC         0.000000
Date Rptd        0.000000
DR_NO            0.000000
TIME OCC         0.000000
Rpt Dist No      0.000000
Vict Age         0.000000
Part 1-2         0.000000
Crm Cd           0.000000
Crm Cd Desc      0.000000
Status Desc      0.000000
LOCATION         0.000000
LAT              0.000000
LON              0.000000
dtype: float64

## vorm van datum netjes gemaakt + kolommen jaar en maand toegevoegd

In [ ]:
df_nypd["arrest_date"] = pd.to_datetime(df_nypd["ARREST_DATE"])
df_lapd["DATE OCC"] = pd.to_datetime(df_lapd["DATE OCC"])

C:\Users\lisah\AppData\Local\Temp\ipykernel_17596\2118804888.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_lapd["DATE OCC"] = pd.to_datetime(df_lapd["DATE OCC"])

In [ ]:
df_nypd["ARREST_DATE"].head(10)

0    12/31/2025
1    12/31/2025
2    12/31/2025
3    12/31/2025
4    12/31/2025
5    12/31/2025
6    12/31/2025
7    12/31/2025
8    12/31/2025
9    12/31/2025
Name: ARREST_DATE, dtype: str

In [ ]:
df_lapd["DATE OCC"].head(10)

0   2020-11-07
1   2020-10-18
2   2020-10-30
3   2020-12-24
4   2020-09-29
5   2020-11-11
6   2020-04-16
7   2020-07-07
8   2020-03-02
9   2020-09-01
Name: DATE OCC, dtype: datetime64[us]

In [ ]:
print(df_nypd["ARREST_DATE"].dropna().iloc[:10].tolist())
print(df_lapd["DATE OCC"].dropna().iloc[:10].tolist())

['12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025']
[Timestamp('2020-11-07 00:00:00'), Timestamp('2020-10-18 00:00:00'), Timestamp('2020-10-30 00:00:00'), Timestamp('2020-12-24 00:00:00'), Timestamp('2020-09-29 00:00:00'), Timestamp('2020-11-11 00:00:00'), Timestamp('2020-04-16 00:00:00'), Timestamp('2020-07-07 00:00:00'), Timestamp('2020-03-02 00:00:00'), Timestamp('2020-09-01 00:00:00')]

In [ ]:
df_nypd["ARREST_DATE"] = pd.to_datetime(
    df_nypd["ARREST_DATE"],
    format="%m/%d/%Y"
)

In [ ]:
df_nypd["ARREST_DATE"].dtype

dtype('<M8[us]')

In [ ]:
df_lapd["DATE OCC"].dtype

dtype('<M8[us]')

In [ ]:
df_nypd["year"] = df_nypd["ARREST_DATE"].dt.year
df_nypd["month"] = df_nypd["ARREST_DATE"].dt.month

df_lapd["year"] = df_lapd["DATE OCC"].dt.year
df_lapd["month"] = df_lapd["DATE OCC"].dt.month

In [ ]:
df_nypd = df_nypd[
    (df_nypd['ARREST_DATE'].dt.year >= 2020) &
    (df_nypd['ARREST_DATE'].dt.year <= 2023)
]
print(f"NYPD gefilterd: {len(df_nypd)} rijen")

NYPD gefilterd: 712075 rijen

In [ ]:
df_lapd = df_lapd[
    (df_lapd['DATE OCC'].dt.year >= 2020) &
    (df_lapd['DATE OCC'].dt.year <= 2023)
]

print(f"LAPD gefilterd: {len(df_lapd)} rijen")

LAPD gefilterd: 877327 rijen

In [ ]:
df_nypd = df_nypd[[
    'ARREST_DATE',
    'OFNS_DESC',
    'LAW_CAT_CD',
    'ARREST_BORO',
    'AGE_GROUP',
    'PERP_SEX',
    'PERP_RACE',
    'Latitude',
    'Longitude',
    'year',
    'month'
]]

df_lapd = df_lapd[[
    'DATE OCC',
    'Crm Cd Desc',
    'Part 1-2',
    'AREA NAME',
    'Vict Age',
    'Vict Sex',
    'Vict Descent',
    'LAT',
    'LON',
    'year',
    'month'
]]

print(df_nypd.shape)
print(df_lapd.shape)

(712075, 11)
(877327, 11)

In [ ]:
df_nypd.to_csv("../data/processed/crime_ny_processed")
df_lapd.to_csv("../data/processed/crime_la_processed")