# Datasetbeschrijving 

Voor dit onderzoek is gebruikgemaakt van twee datasets.

## Los Angeles

Voor dit onderzoek is gebruikgemaakt van de dataset **"Crime Data from 2020 to 2024"**, beschikbaar gesteld door de Los Angeles Police Department (LAPD). De dataset bevat informatie over geregistreerde misdrijven in de stad Los Angeles tussen 2020 en 2024. Elke rij vertegenwoordigt één geregistreerd misdrijf. De dataset bevat ongeveer **1 miljoen observaties (rijen)** en **28 variabelen (kolommen)**.

### Variabelen in de dataset

#### 1. Identificatie van het misdrijf

Deze variabelen identificeren een specifiek politieverslag:

- **dr_no**: uniek dossiernummer van het misdrijf.
- **part_1_2**: classificatie van het misdrijf volgens de FBI-indeling (*Part I* of *Part II*).

#### 2. Tijdsgegevens

Deze variabelen beschrijven wanneer het misdrijf plaatsvond en wanneer het werd gemeld:

- **date_rptd**: datum waarop het misdrijf werd gemeld.
- **date_occ**: datum waarop het misdrijf plaatsvond.
- **time_occ**: tijdstip waarop het misdrijf plaatsvond.

#### 3. Locatiegegevens

Deze variabelen beschrijven waar het misdrijf plaatsvond:

- **area**: nummer van het LAPD-politiegebied.
- **area_name**: naam van het politiegebied.
- **rpt_dist_no**: rapportagedistrict binnen het politiegebied.
- **location**: afgerond adres van het incident.
- **cross_street**: dichtstbijzijnde kruising.
- **lat**: breedtegraad van de locatie.
- **lon**: lengtegraad van de locatie.

#### 4. Misdrijfkenmerken

Deze variabelen beschrijven het gepleegde misdrijf:

- **crm_cd**: code van het misdrijf.
- **crm_cd_desc**: beschrijving van het misdrijf.
- **crm_cd_1**: primaire misdrijfcode.
- **crm_cd_2**, **crm_cd_3**, **crm_cd_4**: eventuele aanvullende misdrijfcodes.
- **mocodes**: modus-operandi-codes die aangeven hoe het misdrijf werd gepleegd.

#### 5. Slachtofferkenmerken

Deze variabelen beschrijven kenmerken van het slachtoffer:

- **vict_age**: leeftijd van het slachtoffer.
- **vict_sex**: geslacht van het slachtoffer.
- **vict_descent**: etnische of culturele achtergrond van het slachtoffer.

#### 6. Overige incidentkenmerken

Deze variabelen geven aanvullende informatie over het incident:

- **premis_cd** en **premis_desc**: type locatie waar het misdrijf plaatsvond.
- **weapon_used_cd** en **weapon_desc**: informatie over een eventueel gebruikt wapen.
- **status** en **status_desc**: status van de zaak.

### Geselecteerde variabelen

Niet alle variabelen zijn relevant voor het onderzoek. Daarom is een selectie gemaakt van de variabelen die het beste aansluiten bij het analyseren van verschillen in criminaliteit tussen gebieden en slachtofferprofielen.

| Variabele | Doel |
|------------|------|
| `date_occ` | Bepalen wanneer een misdrijf plaatsvond |
| `crm_cd_desc` | Het type misdrijf analyseren |
| `part_1_2` | Onderscheid maken tussen ernstigere en minder ernstige misdrijven |
| `area_name` | Criminaliteit tussen verschillende politiegebieden vergelijken |
| `vict_age` | Leeftijdsverschillen tussen slachtoffers onderzoeken |
| `vict_sex` | Verschillen tussen mannelijke en vrouwelijke slachtoffers analyseren |
| `vict_descent` | Verschillen in slachtofferachtergrond onderzoeken |
| `lat`, `lon` | Geografische spreiding van misdrijven visualiseren en hotspots identificeren |

Deze variabelen bevatten samen informatie over wanneer een misdrijf plaatsvond, waar het plaatsvond, welk type misdrijf het betrof en wie het slachtoffer was. Hierdoor vormen ze een goede basis voor het beantwoorden van de onderzoeksvraag.

### Afgeleide variabelen

Naast de oorspronkelijke variabelen zijn twee nieuwe variabelen aangemaakt op basis van `date_occ`:

- **year**: het jaar waarin het misdrijf plaatsvond.
- **month**: de maand waarin het misdrijf plaatsvond.

Deze afgeleide variabelen maken het mogelijk om trends en patronen in criminaliteit over verschillende jaren en maanden te onderzoeken.

---

## New York

Voor dit onderzoek is gebruikgemaakt van de dataset "NYPD Arrests Data (Historic)", beschikbaar gesteld door de New York City Police Department (NYPD). De dataset bevat informatie over arrestaties die zijn verricht door de politie in New York City. Elke rij in de dataset vertegenwoordigt één arrestatie. De dataset bevat ongeveer 6,26 miljoen observaties (rijen) en 19 variabelen (kolommen).

### Variabelen in de dataset

#### 1. Tijdsgegevens

Deze variabelen beschrijven wanneer de arrestatie plaatsvond:

- **arrest_date**: exacte datum van de arrestatie.

#### 2. Delict- en juridische kenmerken

Deze variabelen beschrijven het delict waarvoor iemand is gearresteerd:

- **pd_cd**: gedetailleerde interne classificatiecode van het delict.
- **pd_desc**: beschrijving van de PD-code.
- **ky_cd**: algemene classificatiecode van het delict.
- **ofns_desc**: beschrijving van het type overtreding of misdrijf.
- **law_code**: verwijzing naar de relevante wetgeving.
- **law_cat_cd**: ernstcategorie van het delict (*felony*, *misdemeanor* of *violation*).

#### 3. Locatiegegevens

Deze variabelen beschrijven waar de arrestatie plaatsvond:

- **arrest_boro**: stadsdeel waarin de arrestatie plaatsvond (*Bronx, Brooklyn, Manhattan, Queens* of *Staten Island*).
- **arrest_precinct**: politiedistrict waarin de arrestatie plaatsvond.
- **jurisdiction_code**: instantie die verantwoordelijk was voor de arrestatie.
- **x_coord_cd**: X-coördinaat binnen het New York State Plane Coordinate System.
- **y_coord_cd**: Y-coördinaat binnen het New York State Plane Coordinate System.
- **latitude**: breedtegraad.
- **longitude**: lengtegraad.
- **lon_lat**: gecombineerd geografisch punt op basis van latitude en longitude.

#### 4. Kenmerken van de verdachte

Deze variabelen beschrijven de persoon die is gearresteerd:

- **age_group**: leeftijdscategorie van de verdachte.
- **perp_sex**: geslacht van de verdachte.
- **perp_race**: etnische of raciale achtergrond van de verdachte.

### Geselecteerde variabelen

Voor deze analyse is een selectie gemaakt van de variabelen die relevant zijn voor het onderzoeken van verschillen tussen de stadsdelen van New York en de kenmerken van arrestaties.

| Variabele | Doel |
|------------|------|
| `arrest_date` | Bepalen wanneer een arrestatie plaatsvond |
| `ofns_desc` | Het type overtreding of misdrijf analyseren |
| `law_cat_cd` | Onderscheid maken tussen overtredingen, misdrijven en ernstige misdrijven |
| `arrest_boro` | Arrestaties tussen de verschillende stadsdelen vergelijken |
| `age_group` | Leeftijdsverschillen tussen verdachten onderzoeken |
| `perp_sex` | Verschillen tussen mannelijke en vrouwelijke verdachten analyseren |
| `perp_race` | Verschillen in achtergrond van verdachten onderzoeken |
| `latitude`, `longitude` | Geografische spreiding van arrestaties in kaart brengen |

Deze variabelen geven gezamenlijk inzicht in wanneer een arrestatie plaatsvond, waar deze plaatsvond, waarvoor iemand werd gearresteerd en welke kenmerken de verdachte had.

### Afgeleide variabelen

Naast de oorspronkelijke variabelen zijn twee nieuwe variabelen aangemaakt op basis van `arrest_date`:

- **year**: het jaar waarin de arrestatie plaatsvond.
- **month**: de maand waarin de arrestatie plaatsvond.

Deze afgeleide variabelen maken het mogelijk om arrestaties over de tijd te analyseren en trends tussen verschillende jaren en maanden te onderzoeken. Hierdoor kan bijvoorbeeld worden bekeken of bepaalde typen misdrijven vaker voorkomen in specifieke perioden of hoe arrestatiepatronen zich in de loop der jaren hebben ontwikkeld.

# Data voorverwerking
Omdat de datasets erg groot zijn, moeten deze wat verkleind worden. De code hier onder wordt daarvoor gebruikt, echter kan het erg lang duren om te voltooien, dus wordt het aangeraden om de alleen met de bewerkte data te werken.

In [31]:
import pandas as pd
import os

## Dataset Los Angeles

In [32]:
# If file is not downloaded, get directly from source
if not os.path.isfile("../data/raw/crime_la.csv"):
    df_lapd = pd.read_csv("https://data.lacity.org/resource/2nrs-mtv8.csv?$limit=999999999")
    df_lapd.to_csv("../data/raw/crime_la.csv", index=False)
else:
    df_lapd = pd.read_csv("../data/raw/crime_la.csv")

display(df_lapd)
print(df_lapd.columns)

,dr_no,date_rptd,date_occ,time_occ,area,area_name,rpt_dist_no,part_1_2,crm_cd,crm_cd_desc,...,status,status_desc,crm_cd_1,crm_cd_2,crm_cd_3,crm_cd_4,location,cross_street,lat,lon
0,211507896,2021-04-11T00:00:00.000,2020-11-07T00:00:00.000,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN AV,NaN,34.2124,-118.4092
1,201516622,2020-10-21T00:00:00.000,2020-10-18T00:00:00.000,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203
2,240913563,2024-12-10T00:00:00.000,2020-10-30T00:00:00.000,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,NaN,34.1847,-118.4509
3,210704711,2020-12-24T00:00:00.000,2020-12-24T00:00:00.000,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747
4,201418201,2020-10-03T00:00:00.000,2020-09-29T00:00:00.000,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004889,240710284,2024-07-24T00:00:00.000,2024-07-23T00:00:00.000,1400,7,Wilshire,788,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,4000 W 23RD ST,NaN,34.0362,-118.3284
1004890,240104953,2024-01-15T00:00:00.000,2024-01-15T00:00:00.000,100,1,Central,101,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,NaN,NaN,NaN,1300 W SUNSET BL,NaN,34.0685,-118.2460
1004891,240410786,2024-10-14T00:00:00.000,2024-10-11T00:00:00.000,2330,4,Hollenbeck,421,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,NaN,NaN,NaN,1700 ALBION ST,NaN,34.0675,-118.2240
1004892,240309674,2024-04-24T00:00:00.000,2024-04-24T00:00:00.000,1500,3,Southwest,358,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,FLOWER ST,JEFFERSON BL,34.0215,-118.2868
1004893,240910892,2024-08-13T00:00:00.000,2024-08-12T00:00:00.000,2300,9,Van Nuys,914,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,6900 VESPER AV,NaN,34.1961,-118.4510

Index(['dr_no', 'date_rptd', 'date_occ', 'time_occ', 'area', 'area_name',
       'rpt_dist_no', 'part_1_2', 'crm_cd', 'crm_cd_desc', 'mocodes',
       'vict_age', 'vict_sex', 'vict_descent', 'premis_cd', 'premis_desc',
       'weapon_used_cd', 'weapon_desc', 'status', 'status_desc', 'crm_cd_1',
       'crm_cd_2', 'crm_cd_3', 'crm_cd_4', 'location', 'cross_street', 'lat',
       'lon'],
      dtype='str')

## Dataset New York

In [33]:
# If file is not downloaded, get directly from source
if not os.path.isfile("../data/raw/crime_ny.csv"):
    # Limit the dataset to entries starting from 2020
    df_nypd = pd.read_csv("https://data.cityofnewyork.us/resource/8h9b-rp9u.csv?$limit=1252000")
    df_nypd.to_csv("../data/raw/crime_ny.csv", index=False)
else:
    df_nypd = pd.read_csv("../data/raw/crime_ny.csv")

display(df_nypd)
print(df_nypd.columns)

,arrest_key,arrest_date,pd_cd,pd_desc,ky_cd,ofns_desc,law_code,law_cat_cd,arrest_boro,arrest_precinct,jurisdiction_code,age_group,perp_sex,perp_race,x_coord_cd,y_coord_cd,latitude,longitude,lon_lat
0,318190042,2025-12-31T00:00:00.000,113.0,"MENACING,UNCLASSIFIED",344.0,ASSAULT 3 & RELATED OFFENSES,PL 1201401,M,B,44,0,45-64,M,BLACK,1005903,243479,40.834952,-73.921752,POINT (-73.921752 40.834952)
1,318210353,2025-12-31T00:00:00.000,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL051101A,M,K,67,0,25-44,F,BLACK,1006762,178397,40.656307,-73.918865,POINT (-73.91886471 40.65630659)
2,318184096,2025-12-31T00:00:00.000,681.0,"CHILD, ENDANGERING WELFARE",233.0,SEX CRIMES,PL 2601001,M,M,5,0,25-44,M,WHITE HISPANIC,984990,200136,40.716012,-73.997332,POINT (-73.9973320301008 40.7160120119955)
3,318203917,2025-12-31T00:00:00.000,259.0,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",351.0,CRIMINAL MISCHIEF & RELATED OF,PL 1450001,M,B,52,0,25-44,M,BLACK,1014400,256319,40.870159,-73.890987,POINT (-73.8909872 40.8701594)
4,318204909,2025-12-31T00:00:00.000,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,M,M,1,3,25-44,M,WHITE,981073,197959,40.710038,-74.011460,POINT (-74.01146 40.710038)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1251995,206897453,2020-01-01T00:00:00.000,782.0,"WEAPONS, POSSESSION, ETC",236.0,DANGEROUS WEAPONS,PL 2650101,M,M,28,0,<18,M,BLACK,997392,231146,40.801117,-73.952533,POINT (-73.95253345199995 40.801116800000045)
1251996,206891613,2020-01-01T00:00:00.000,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,Q,103,0,25-44,M,WHITE HISPANIC,1041172,197409,40.708344,-73.794689,POINT (-73.79468905999995 40.708343986000045)
1251997,206895760,2020-01-01T00:00:00.000,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,Q,110,0,25-44,M,WHITE HISPANIC,1020917,207643,40.736541,-73.867691,POINT (-73.86769107499998 40.73654093400006)
1251998,206891071,2020-01-01T00:00:00.000,510.0,"CONTROLLED SUBSTANCE, INTENT T",117.0,DANGEROUS DRUGS,PL 2200601,F,B,52,0,25-44,M,BLACK HISPANIC,1014660,254550,40.865311,-73.890057,POINT (-73.89005657399997 40.86531144500003)
1251999,206901266,2020-01-01T00:00:00.000,117.0,RECKLESS ENDANGERMENT 1,126.0,MISCELLANEOUS PENAL LAW,PL 1202500,F,Q,102,0,18-24,M,WHITE HISPANIC,1030953,194101,40.699324,-73.831571,POINT (-73.83157088799999 40.69932415700004)

Index(['arrest_key', 'arrest_date', 'pd_cd', 'pd_desc', 'ky_cd', 'ofns_desc',
       'law_code', 'law_cat_cd', 'arrest_boro', 'arrest_precinct',
       'jurisdiction_code', 'age_group', 'perp_sex', 'perp_race', 'x_coord_cd',
       'y_coord_cd', 'latitude', 'longitude', 'lon_lat'],
      dtype='str')

## Datasets variabelen vergelijken

In [34]:
df_nypd.info()
df_lapd.info()

<class 'pandas.DataFrame'>
RangeIndex: 1252000 entries, 0 to 1251999
Data columns (total 19 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   arrest_key         1252000 non-null  int64
 1   arrest_date        1252000 non-null  str
 2   pd_cd              1251377 non-null  float64
 3   pd_desc            1251860 non-null  str
 4   ky_cd              1251218 non-null  float64
 5   ofns_desc          1251860 non-null  str
 6   law_code           1252000 non-null  str
 7   law_cat_cd         1243008 non-null  str
 8   arrest_boro        1252000 non-null  str
 9   arrest_precinct    1252000 non-null  int64
 10  jurisdiction_code  1252000 non-null  int64
 11  age_group          1252000 non-null  str
 12  perp_sex           1252000 non-null  str
 13  perp_race          1252000 non-null  str
 14  x_coord_cd         1252000 non-null  int64
 15  y_coord_cd         1252000 non-null  int64
 16  latitude           1251996 non-null  float64
 17  longitude          1251996 non-null  float64
 18  lon_lat            1251996 non-null  str
dtypes: float64(4), int64(5), str(10)
memory usage: 181.5 MB
<class 'pandas.DataFrame'>
RangeIndex: 1004894 entries, 0 to 1004893
Data columns (total 28 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   dr_no           1004894 non-null  int64
 1   date_rptd       1004894 non-null  str
 2   date_occ        1004894 non-null  str
 3   time_occ        1004894 non-null  int64
 4   area            1004894 non-null  int64
 5   area_name       1004894 non-null  str
 6   rpt_dist_no     1004894 non-null  int64
 7   part_1_2        1004894 non-null  int64
 8   crm_cd          1004894 non-null  int64
 9   crm_cd_desc     1004894 non-null  str
 10  mocodes         853296 non-null   str
 11  vict_age        1004894 non-null  int64
 12  vict_sex        860263 non-null   str
 13  vict_descent    860251 non-null   str
 14  premis_cd       1004878 non-null  float64
 15  premis_desc     1004306 non-null  str
 16  weapon_used_cd  327216 non-null   float64
 17  weapon_desc     327216 non-null   str
 18  status          1004893 non-null  str
 19  status_desc     1004894 non-null  str
 20  crm_cd_1        1004883 non-null  float64
 21  crm_cd_2        69154 non-null    float64
 22  crm_cd_3        2314 non-null     float64
 23  crm_cd_4        64 non-null       float64
 24  location        1004894 non-null  str
 25  cross_street    154228 non-null   str
 26  lat             1004894 non-null  float64
 27  lon             1004894 non-null  float64
dtypes: float64(8), int64(7), str(13)
memory usage: 214.7 MB

In [35]:
df_nypd.columns.tolist()
df_lapd.columns.tolist()

['dr_no',
 'date_rptd',
 'date_occ',
 'time_occ',
 'area',
 'area_name',
 'rpt_dist_no',
 'part_1_2',
 'crm_cd',
 'crm_cd_desc',
 'mocodes',
 'vict_age',
 'vict_sex',
 'vict_descent',
 'premis_cd',
 'premis_desc',
 'weapon_used_cd',
 'weapon_desc',
 'status',
 'status_desc',
 'crm_cd_1',
 'crm_cd_2',
 'crm_cd_3',
 'crm_cd_4',
 'location',
 'cross_street',
 'lat',
 'lon']

In [36]:
comparison = pd.DataFrame({
    "NYPD": pd.Series(df_nypd.columns),
    "LAPD": pd.Series(df_lapd.columns)
})

comparison

                 NYPD            LAPD
0          arrest_key           dr_no
1         arrest_date       date_rptd
2               pd_cd        date_occ
3             pd_desc        time_occ
4               ky_cd            area
5           ofns_desc       area_name
6            law_code     rpt_dist_no
7          law_cat_cd        part_1_2
8         arrest_boro          crm_cd
9     arrest_precinct     crm_cd_desc
10  jurisdiction_code         mocodes
11          age_group        vict_age
12           perp_sex        vict_sex
13          perp_race    vict_descent
14         x_coord_cd       premis_cd
15         y_coord_cd     premis_desc
16           latitude  weapon_used_cd
17          longitude     weapon_desc
18            lon_lat          status
19                NaN     status_desc
20                NaN        crm_cd_1
21                NaN        crm_cd_2
22                NaN        crm_cd_3
23                NaN        crm_cd_4
24                NaN        location
25                NaN    cross_street
26                NaN             lat
27                NaN             lon

# missing values bekijken

In [37]:
missing_nypd = (
    df_nypd.isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

missing_lapd = (
    df_lapd.isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)
print(missing_nypd)
print(missing_lapd)

law_cat_cd           0.718211
ky_cd                0.062460
pd_cd                0.049760
ofns_desc            0.011182
pd_desc              0.011182
lon_lat              0.000319
latitude             0.000319
longitude            0.000319
arrest_key           0.000000
arrest_date          0.000000
law_code             0.000000
jurisdiction_code    0.000000
arrest_precinct      0.000000
arrest_boro          0.000000
age_group            0.000000
x_coord_cd           0.000000
perp_race            0.000000
perp_sex             0.000000
y_coord_cd           0.000000
dtype: float64
crm_cd_4          99.993631
crm_cd_3          99.769727
crm_cd_2          93.118279
cross_street      84.652312
weapon_used_cd    67.437760
weapon_desc       67.437760
mocodes           15.085969
vict_descent      14.393856
vict_sex          14.392662
premis_desc        0.058514
premis_cd          0.001592
crm_cd_1           0.001095
status             0.000100
vict_age           0.000000
crm_cd             0.000000
crm_cd_desc        0.000000
area_name          0.000000
rpt_dist_no        0.000000
area               0.000000
time_occ           0.000000
date_rptd          0.000000
date_occ           0.000000
dr_no              0.000000
part_1_2           0.000000
status_desc        0.000000
location           0.000000
lat                0.000000
lon                0.000000
dtype: float64

In [38]:
threshold = 0.5

df_nypd = df_nypd.loc[:, df_nypd.isna().mean() < threshold]

In [39]:
threshold = 0.5

df_lapd = df_lapd.loc[:, df_lapd.isna().mean() < threshold]

In [40]:
print(df_nypd.columns.tolist())
print(df_lapd.columns.tolist())

['arrest_key', 'arrest_date', 'pd_cd', 'pd_desc', 'ky_cd', 'ofns_desc', 'law_code', 'law_cat_cd', 'arrest_boro', 'arrest_precinct', 'jurisdiction_code', 'age_group', 'perp_sex', 'perp_race', 'x_coord_cd', 'y_coord_cd', 'latitude', 'longitude', 'lon_lat']
['dr_no', 'date_rptd', 'date_occ', 'time_occ', 'area', 'area_name', 'rpt_dist_no', 'part_1_2', 'crm_cd', 'crm_cd_desc', 'mocodes', 'vict_age', 'vict_sex', 'vict_descent', 'premis_cd', 'premis_desc', 'status', 'status_desc', 'crm_cd_1', 'location', 'lat', 'lon']

In [41]:
(df_nypd.isna().mean() * 100).sort_values(ascending=False)

law_cat_cd           0.718211
ky_cd                0.062460
pd_cd                0.049760
ofns_desc            0.011182
pd_desc              0.011182
lon_lat              0.000319
latitude             0.000319
longitude            0.000319
arrest_key           0.000000
arrest_date          0.000000
law_code             0.000000
jurisdiction_code    0.000000
arrest_precinct      0.000000
arrest_boro          0.000000
age_group            0.000000
x_coord_cd           0.000000
perp_race            0.000000
perp_sex             0.000000
y_coord_cd           0.000000
dtype: float64

In [42]:
(df_lapd.isna().mean() * 100).sort_values(ascending=False)

mocodes         15.085969
vict_descent    14.393856
vict_sex        14.392662
premis_desc      0.058514
premis_cd        0.001592
crm_cd_1         0.001095
status           0.000100
area             0.000000
area_name        0.000000
date_occ         0.000000
date_rptd        0.000000
dr_no            0.000000
time_occ         0.000000
rpt_dist_no      0.000000
vict_age         0.000000
part_1_2         0.000000
crm_cd           0.000000
crm_cd_desc      0.000000
status_desc      0.000000
location         0.000000
lat              0.000000
lon              0.000000
dtype: float64

## vorm van datum netjes gemaakt + kolommen jaar en maand toegevoegd

In [43]:
df_nypd["arrest_date"] = pd.to_datetime(df_nypd["ARREST_DATE"])
df_lapd["DATE OCC"] = pd.to_datetime(df_lapd["DATE OCC"])

KeyError: 'ARREST_DATE'

In [ ]:
df_nypd["ARREST_DATE"].head(10)

0    12/31/2025
1    12/31/2025
2    12/31/2025
3    12/31/2025
4    12/31/2025
5    12/31/2025
6    12/31/2025
7    12/31/2025
8    12/31/2025
9    12/31/2025
Name: ARREST_DATE, dtype: str

In [ ]:
df_lapd["DATE OCC"].head(10)

0   2020-11-07
1   2020-10-18
2   2020-10-30
3   2020-12-24
4   2020-09-29
5   2020-11-11
6   2020-04-16
7   2020-07-07
8   2020-03-02
9   2020-09-01
Name: DATE OCC, dtype: datetime64[us]

In [ ]:
print(df_nypd["ARREST_DATE"].dropna().iloc[:10].tolist())
print(df_lapd["DATE OCC"].dropna().iloc[:10].tolist())

['12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025']
[Timestamp('2020-11-07 00:00:00'), Timestamp('2020-10-18 00:00:00'), Timestamp('2020-10-30 00:00:00'), Timestamp('2020-12-24 00:00:00'), Timestamp('2020-09-29 00:00:00'), Timestamp('2020-11-11 00:00:00'), Timestamp('2020-04-16 00:00:00'), Timestamp('2020-07-07 00:00:00'), Timestamp('2020-03-02 00:00:00'), Timestamp('2020-09-01 00:00:00')]

In [ ]:
df_nypd["ARREST_DATE"] = pd.to_datetime(
    df_nypd["ARREST_DATE"],
    format="%m/%d/%Y"
)

In [ ]:
df_nypd["ARREST_DATE"].dtype

dtype('<M8[us]')

In [ ]:
df_lapd["DATE OCC"].dtype

dtype('<M8[us]')

In [ ]:
df_nypd["year"] = df_nypd["ARREST_DATE"].dt.year
df_nypd["month"] = df_nypd["ARREST_DATE"].dt.month

df_lapd["year"] = df_lapd["DATE OCC"].dt.year
df_lapd["month"] = df_lapd["DATE OCC"].dt.month

In [ ]:
df_nypd = df_nypd[
    (df_nypd['ARREST_DATE'].dt.year >= 2020) &
    (df_nypd['ARREST_DATE'].dt.year <= 2023)
]
print(f"NYPD gefilterd: {len(df_nypd)} rijen")

NYPD gefilterd: 712075 rijen

In [ ]:
df_lapd = df_lapd[
    (df_lapd['DATE OCC'].dt.year >= 2020) &
    (df_lapd['DATE OCC'].dt.year <= 2023)
]

print(f"LAPD gefilterd: {len(df_lapd)} rijen")

LAPD gefilterd: 877327 rijen

In [ ]:
df_nypd = df_nypd[[
    'ARREST_DATE',
    'OFNS_DESC',
    'LAW_CAT_CD',
    'ARREST_BORO',
    'AGE_GROUP',
    'PERP_SEX',
    'PERP_RACE',
    'Latitude',
    'Longitude',
    'year',
    'month'
]]

df_lapd = df_lapd[[
    'DATE OCC',
    'Crm Cd Desc',
    'Part 1-2',
    'AREA NAME',
    'Vict Age',
    'Vict Sex',
    'Vict Descent',
    'LAT',
    'LON',
    'year',
    'month'
]]

print(df_nypd.shape)
print(df_lapd.shape)

(712075, 11)
(877327, 11)

In [44]:
df_nypd.to_csv("../data/processed/crime_ny_processed.csv", index=False)
df_lapd.to_csv("../data/processed/crime_la_processed.csv", index=False)