# Introductie

In dit onderzoek worden criminaliteitspatronen in twee grote Amerikaanse steden, New York en Los Angeles, met elkaar vergeleken aan de hand van uitgebreide politiedatasets.
De analyse is opgebouwd rond twee hoofdargumenten. Ten eerste wordt gekeken of New York daadwerkelijk meer criminaliteit kent dan Los Angeles, en welke stedelijke factoren zoals bevolkingsdichtheid, toerisme en sociaaleconomische omstandigheden dit kunnen verklaren. Ten tweede wordt onderzocht hoe groot de verschillen in criminaliteit binnen de steden zelf zijn, waarbij de nadruk ligt op wijk- en stadsdeelniveau en de invloed van lokale sociaaleconomische omstandigheden.
Door gebruik te maken van gedetailleerde gegevens over incidenten, arrestaties, locaties en betrokken personen, wordt geprobeerd om niet alleen gemiddelden te vergelijken, maar ook onderliggende patronen zichtbaar te maken. Op deze manier ontstaat een genuanceerder beeld van criminaliteit binnen en tussen beide steden.

# Datasetbeschrijving 

## Los Angeles

Voor dit onderzoek is gebruikgemaakt van de dataset **"Crime Data from 2020 to 2024"**, beschikbaar gesteld door de Los Angeles Police Department (LAPD). De dataset bevat informatie over geregistreerde misdrijven in de stad Los Angeles tussen 2020 en 2024. Elke rij vertegenwoordigt één geregistreerd misdrijf. De dataset bevat ongeveer **1 miljoen observaties (rijen)** en **28 variabelen (kolommen)**.

### Variabelen in de dataset

#### 1. Identificatie van het misdrijf

Deze variabelen identificeren een specifiek politieverslag:

- **dr_no**: uniek dossiernummer van het misdrijf.
- **part_1_2**: classificatie van het misdrijf volgens de FBI-indeling (*Part I* of *Part II*).

#### 2. Tijdsgegevens

Deze variabelen beschrijven wanneer het misdrijf plaatsvond en wanneer het werd gemeld:

- **date_rptd**: datum waarop het misdrijf werd gemeld.
- **date_occ**: datum waarop het misdrijf plaatsvond.
- **time_occ**: tijdstip waarop het misdrijf plaatsvond.

#### 3. Locatiegegevens

Deze variabelen beschrijven waar het misdrijf plaatsvond:

- **area**: nummer van het LAPD-politiegebied.
- **area_name**: naam van het politiegebied.
- **rpt_dist_no**: rapportagedistrict binnen het politiegebied.
- **location**: afgerond adres van het incident.
- **cross_street**: dichtstbijzijnde kruising.
- **lat**: breedtegraad van de locatie.
- **lon**: lengtegraad van de locatie.

#### 4. Misdrijfkenmerken

Deze variabelen beschrijven het gepleegde misdrijf:

- **crm_cd**: code van het misdrijf.
- **crm_cd_desc**: beschrijving van het misdrijf.
- **crm_cd_1**: primaire misdrijfcode.
- **crm_cd_2**, **crm_cd_3**, **crm_cd_4**: eventuele aanvullende misdrijfcodes.
- **mocodes**: modus-operandi-codes die aangeven hoe het misdrijf werd gepleegd.

#### 5. Slachtofferkenmerken

Deze variabelen beschrijven kenmerken van het slachtoffer:

- **vict_age**: leeftijd van het slachtoffer.
- **vict_sex**: geslacht van het slachtoffer.
- **vict_descent**: etnische of culturele achtergrond van het slachtoffer.

#### 6. Overige incidentkenmerken

Deze variabelen geven aanvullende informatie over het incident:

- **premis_cd** en **premis_desc**: type locatie waar het misdrijf plaatsvond.
- **weapon_used_cd** en **weapon_desc**: informatie over een eventueel gebruikt wapen.
- **status** en **status_desc**: status van de zaak.

### Geselecteerde variabelen

Niet alle variabelen zijn relevant voor het onderzoek. Daarom is een selectie gemaakt van de variabelen die het beste aansluiten bij het analyseren van verschillen in criminaliteit tussen gebieden en slachtofferprofielen.

| Variabele | Doel |
|------------|------|
| `date_occ` | Bepalen wanneer een misdrijf plaatsvond |
| `crm_cd_desc` | Het type misdrijf analyseren |
| `part_1_2` | Onderscheid maken tussen ernstigere en minder ernstige misdrijven |
| `area_name` | Criminaliteit tussen verschillende politiegebieden vergelijken |
| `vict_age` | Leeftijdsverschillen tussen slachtoffers onderzoeken |
| `vict_sex` | Verschillen tussen mannelijke en vrouwelijke slachtoffers analyseren |
| `vict_descent` | Verschillen in slachtofferachtergrond onderzoeken |
| `lat`, `lon` | Geografische spreiding van misdrijven visualiseren en hotspots identificeren |

Deze variabelen bevatten samen informatie over wanneer een misdrijf plaatsvond, waar het plaatsvond, welk type misdrijf het betrof en wie het slachtoffer was. Hierdoor vormen ze een goede basis voor het beantwoorden van de onderzoeksvraag.

### Afgeleide variabelen

Naast de oorspronkelijke variabelen zijn twee nieuwe variabelen aangemaakt op basis van `date_occ`:

- **year**: het jaar waarin het misdrijf plaatsvond.
- **month**: de maand waarin het misdrijf plaatsvond.

Deze afgeleide variabelen maken het mogelijk om trends en patronen in criminaliteit over verschillende jaren en maanden te onderzoeken.

---

## New York

Voor dit onderzoek is gebruikgemaakt van de dataset "NYPD Arrests Data (Historic)", beschikbaar gesteld door de New York City Police Department (NYPD). De dataset bevat informatie over arrestaties die zijn verricht door de politie in New York City. Elke rij in de dataset vertegenwoordigt één arrestatie. De dataset bevat ongeveer 6,26 miljoen observaties (rijen) en 19 variabelen (kolommen).

### Variabelen in de dataset

#### 1. Tijdsgegevens

Deze variabelen beschrijven wanneer de arrestatie plaatsvond:

- **arrest_date**: exacte datum van de arrestatie.

#### 2. Delict- en juridische kenmerken

Deze variabelen beschrijven het delict waarvoor iemand is gearresteerd:

- **pd_cd**: gedetailleerde interne classificatiecode van het delict.
- **pd_desc**: beschrijving van de PD-code.
- **ky_cd**: algemene classificatiecode van het delict.
- **ofns_desc**: beschrijving van het type overtreding of misdrijf.
- **law_code**: verwijzing naar de relevante wetgeving.
- **law_cat_cd**: ernstcategorie van het delict (*felony*, *misdemeanor* of *violation*).

#### 3. Locatiegegevens

Deze variabelen beschrijven waar de arrestatie plaatsvond:

- **arrest_boro**: stadsdeel waarin de arrestatie plaatsvond (*Bronx, Brooklyn, Manhattan, Queens* of *Staten Island*).
- **arrest_precinct**: politiedistrict waarin de arrestatie plaatsvond.
- **jurisdiction_code**: instantie die verantwoordelijk was voor de arrestatie.
- **x_coord_cd**: X-coördinaat binnen het New York State Plane Coordinate System.
- **y_coord_cd**: Y-coördinaat binnen het New York State Plane Coordinate System.
- **latitude**: breedtegraad.
- **longitude**: lengtegraad.
- **lon_lat**: gecombineerd geografisch punt op basis van latitude en longitude.

#### 4. Kenmerken van de verdachte

Deze variabelen beschrijven de persoon die is gearresteerd:

- **age_group**: leeftijdscategorie van de verdachte.
- **perp_sex**: geslacht van de verdachte.
- **perp_race**: etnische of raciale achtergrond van de verdachte.

### Geselecteerde variabelen

Voor deze analyse is een selectie gemaakt van de variabelen die relevant zijn voor het onderzoeken van verschillen tussen de stadsdelen van New York en de kenmerken van arrestaties.

| Variabele | Doel |
|------------|------|
| `arrest_date` | Bepalen wanneer een arrestatie plaatsvond |
| `ofns_desc` | Het type overtreding of misdrijf analyseren |
| `law_cat_cd` | Onderscheid maken tussen overtredingen, misdrijven en ernstige misdrijven |
| `arrest_boro` | Arrestaties tussen de verschillende stadsdelen vergelijken |
| `age_group` | Leeftijdsverschillen tussen verdachten onderzoeken |
| `perp_sex` | Verschillen tussen mannelijke en vrouwelijke verdachten analyseren |
| `perp_race` | Verschillen in achtergrond van verdachten onderzoeken |
| `latitude`, `longitude` | Geografische spreiding van arrestaties in kaart brengen |

Deze variabelen geven gezamenlijk inzicht in wanneer een arrestatie plaatsvond, waar deze plaatsvond, waarvoor iemand werd gearresteerd en welke kenmerken de verdachte had.

### Afgeleide variabelen

Naast de oorspronkelijke variabelen zijn twee nieuwe variabelen aangemaakt op basis van `arrest_date`:

- **year**: het jaar waarin de arrestatie plaatsvond.
- **month**: de maand waarin de arrestatie plaatsvond.

Deze afgeleide variabelen maken het mogelijk om arrestaties over de tijd te analyseren en trends tussen verschillende jaren en maanden te onderzoeken. Hierdoor kan bijvoorbeeld worden bekeken of bepaalde typen misdrijven vaker voorkomen in specifieke perioden of hoe arrestatiepatronen zich in de loop der jaren hebben ontwikkeld.

# Argument 1
New York heeft meer criminaliteit dan Los Angeles
## Perspectief
New York heeft een zeer hoge bevolkingsdichtheid, waardoor veel mensen dagelijks dicht op elkaar leven en werken. Dit vergroot de kans op criminaliteit, zoals diefstal, zakkenrollerij en andere veelvoorkomende misdrijven. Daarnaast trekt de stad jaarlijks miljoenen toeristen aan, wat extra mogelijkheden biedt voor bepaalde vormen van criminaliteit. Ook spelen sociaaleconomische problemen, zoals armoede en bendecriminaliteit in sommige wijken, een rol. Door de grote omvang, drukte en constante stroom van inwoners en bezoekers is het voor politie en andere instanties een uitdaging om criminaliteit volledig te voorkomen.
# Argument 2
De verschillen in criminaliteit tussen wijken zijn groot, zowel in New York als in Los Angeles.
## Perspectief
Criminaliteit is niet gelijk verdeeld over een stad. Sommige wijken kennen relatief weinig misdrijven, terwijl andere buurten juist vaker met criminaliteit te maken hebben. Factoren zoals inkomen, werkgelegenheid, onderwijsniveau en de beschikbaarheid van voorzieningen kunnen hierbij een belangrijke rol spelen. Zowel in New York als in Los Angeles bestaan grote sociaaleconomische verschillen tussen wijken. Gebieden waarin meer wordt geïnvesteerd in openbare voorzieningen, sociale programma’s en veiligheid laten vaak lagere criminaliteitscijfers zien. Daardoor geeft een gemiddeld criminaliteitscijfer voor een hele stad niet altijd een nauwkeurig beeld van de veiligheid op wijkniveau.

In [55]:
import plotly.graph_objs as go
import plotly.express as px
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import io
import base64
from plotly.subplots import make_subplots
from dash import Dash, dcc, html, Input, Output
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)

# Inladen van datasets

## Dataset Los Angeles

In [56]:
df_lapd = pd.read_csv('../data/Crime_Data_from_2020_to_2024.csv')
display(df_lapd)
print(df_lapd.columns)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,211507896,04/11/2021 12:00:00 AM,11/07/2020 12:00:00 AM,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN AV,NaN,34.2124,-118.4092
1,201516622,10/21/2020 12:00:00 AM,10/18/2020 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203
2,240913563,12/10/2024 12:00:00 AM,10/30/2020 12:00:00 AM,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,NaN,34.1847,-118.4509
3,210704711,12/24/2020 12:00:00 AM,12/24/2020 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747
4,201418201,10/03/2020 12:00:00 AM,09/29/2020 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004889,240710284,07/24/2024 12:00:00 AM,07/23/2024 12:00:00 AM,1400,7,Wilshire,788,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,4000 W 23RD ST,NaN,34.0362,-118.3284
1004890,240104953,01/15/2024 12:00:00 AM,01/15/2024 12:00:00 AM,100,1,Central,101,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,NaN,NaN,NaN,1300 W SUNSET BL,NaN,34.0685,-118.2460
1004891,240410786,10/14/2024 12:00:00 AM,10/11/2024 12:00:00 AM,2330,4,Hollenbeck,421,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,NaN,NaN,NaN,1700 ALBION ST,NaN,34.0675,-118.2240
1004892,240309674,04/24/2024 12:00:00 AM,04/24/2024 12:00:00 AM,1500,3,Southwest,358,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,FLOWER ST,JEFFERSON BL,34.0215,-118.2868
1004893,240910892,08/13/2024 12:00:00 AM,08/12/2024 12:00:00 AM,2300,9,Van Nuys,914,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,6900 VESPER AV,NaN,34.1961,-118.4510

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON'],
      dtype='str')

## Dataset New York

In [57]:
df_nypd = pd.read_csv('../data/NYPD_Arrests_Data_(Historic)_20260613.csv')
display(df_nypd)
print(df_nypd.columns)

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lon_Lat
0,318178990,12/31/2025,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,47,0,<18,F,BLACK,1023593,261233,"40,883621","-73,85772",POINT (-73.85772 40.883621)
1,318203916,12/31/2025,494.0,"STOLEN PROPERTY 2,1,POSSESSION",111.0,POSSESSION OF STOLEN PROPERTY,PL 1655000,F,B,40,0,25-44,M,BLACK,1006229,234035,"40,809029","-73,920603",POINT (-73.920603 40.809029)
2,318196542,12/31/2025,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,40,2,(null),(null),BLACK,1010515,236824,"40,816674","-73,905109",POINT (-73.905109 40.816674)
3,318196547,12/31/2025,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,K,77,0,45-64,M,BLACK,1003508,185056,"40,674601","-73,930573",POINT (-73.930573 40.674601)
4,318200237,12/31/2025,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,M,M,19,0,45-64,M,BLACK,996772,223148,"40,779168","-73,954785",POINT (-73.954785 40.779168)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1251526,206906423,01/02/2020,273.0,"TAMPERING 1,CRIMINAL",121.0,CRIMINAL MISCHIEF & RELATED OF,PL 1452000,F,M,1,1,25-44,M,WHITE,982806,201821,"40,720636846","-74,005210778",POINT (-74.00521077799993 40.72063684600005)
1251527,206904269,01/02/2020,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,M,Q,106,0,45-64,M,WHITE HISPANIC,1029794,186424,"40,67825863","-73,835802613",POINT (-73.83580261299994 40.67825863000007)
1251528,206904271,01/02/2020,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL1220B01,M,Q,115,3,45-64,M,AMERICAN INDIAN/ALASKAN NATIVE,1018623,214936,"40,756567585","-73,875931534",POINT (-73.87593153399997 40.75656758500002)
1251529,206901720,01/02/2020,681.0,"CHILD, ENDANGERING WELFARE",233.0,SEX CRIMES,PL 2601001,M,Q,102,0,25-44,M,ASIAN / PACIFIC ISLANDER,1030954,193887,"40,698736773","-73,831568765",POINT (-73.83156876499999 40.698736773000064)
1251530,206898851,01/02/2020,209.0,"BURGLARS TOOLS,UNCLASSIFIED",231.0,BURGLAR'S TOOLS,PL 1403500,M,B,40,0,18-24,M,BLACK HISPANIC,1006572,231983,"40,803395714","-73,919373155",POINT (-73.91937315499997 40.80339571400003)

Index(['ARREST_KEY', 'ARREST_DATE', 'PD_CD', 'PD_DESC', 'KY_CD', 'OFNS_DESC',
       'LAW_CODE', 'LAW_CAT_CD', 'ARREST_BORO', 'ARREST_PRECINCT',
       'JURISDICTION_CODE', 'AGE_GROUP', 'PERP_SEX', 'PERP_RACE', 'X_COORD_CD',
       'Y_COORD_CD', 'Latitude', 'Longitude', 'Lon_Lat'],
      dtype='str')

## Datasets variabelen vergelijken

In [58]:
df_nypd.info()
df_lapd.info()

<class 'pandas.DataFrame'>
RangeIndex: 1251531 entries, 0 to 1251530
Data columns (total 19 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ARREST_KEY         1251531 non-null  int64
 1   ARREST_DATE        1251531 non-null  str
 2   PD_CD              1250908 non-null  float64
 3   PD_DESC            1251391 non-null  str
 4   KY_CD              1250749 non-null  float64
 5   OFNS_DESC          1251391 non-null  str
 6   LAW_CODE           1251531 non-null  str
 7   LAW_CAT_CD         1242539 non-null  str
 8   ARREST_BORO        1251531 non-null  str
 9   ARREST_PRECINCT    1251531 non-null  int64
 10  JURISDICTION_CODE  1251531 non-null  int64
 11  AGE_GROUP          1251531 non-null  str
 12  PERP_SEX           1251531 non-null  str
 13  PERP_RACE          1251531 non-null  str
 14  X_COORD_CD         1251531 non-null  int64
 15  Y_COORD_CD         1251531 non-null  int64
 16  Latitude           1251527 non-null  str
 17  Longitude          1251527 non-null  str
 18  Lon_Lat            1251527 non-null  str
dtypes: float64(2), int64(5), str(12)
memory usage: 181.4 MB
<class 'pandas.DataFrame'>
RangeIndex: 1004894 entries, 0 to 1004893
Data columns (total 28 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   DR_NO           1004894 non-null  int64
 1   Date Rptd       1004894 non-null  str
 2   DATE OCC        1004894 non-null  str
 3   TIME OCC        1004894 non-null  int64
 4   AREA            1004894 non-null  int64
 5   AREA NAME       1004894 non-null  str
 6   Rpt Dist No     1004894 non-null  int64
 7   Part 1-2        1004894 non-null  int64
 8   Crm Cd          1004894 non-null  int64
 9   Crm Cd Desc     1004894 non-null  str
 10  Mocodes         853296 non-null   str
 11  Vict Age        1004894 non-null  int64
 12  Vict Sex        860263 non-null   str
 13  Vict Descent    860251 non-null   str
 14  Premis Cd       1004878 non-null  float64
 15  Premis Desc     1004306 non-null  str
 16  Weapon Used Cd  327216 non-null   float64
 17  Weapon Desc     327216 non-null   str
 18  Status          1004893 non-null  str
 19  Status Desc     1004894 non-null  str
 20  Crm Cd 1        1004883 non-null  float64
 21  Crm Cd 2        69154 non-null    float64
 22  Crm Cd 3        2314 non-null     float64
 23  Crm Cd 4        64 non-null       float64
 24  LOCATION        1004894 non-null  str
 25  Cross Street    154228 non-null   str
 26  LAT             1004894 non-null  float64
 27  LON             1004894 non-null  float64
dtypes: float64(8), int64(7), str(13)
memory usage: 214.7 MB

In [59]:
df_nypd.columns.tolist()
df_lapd.columns.tolist()

['DR_NO',
 'Date Rptd',
 'DATE OCC',
 'TIME OCC',
 'AREA',
 'AREA NAME',
 'Rpt Dist No',
 'Part 1-2',
 'Crm Cd',
 'Crm Cd Desc',
 'Mocodes',
 'Vict Age',
 'Vict Sex',
 'Vict Descent',
 'Premis Cd',
 'Premis Desc',
 'Weapon Used Cd',
 'Weapon Desc',
 'Status',
 'Status Desc',
 'Crm Cd 1',
 'Crm Cd 2',
 'Crm Cd 3',
 'Crm Cd 4',
 'LOCATION',
 'Cross Street',
 'LAT',
 'LON']

In [60]:
comparison = pd.DataFrame({
    "NYPD": pd.Series(df_nypd.columns),
    "LAPD": pd.Series(df_lapd.columns)
})

comparison

                 NYPD            LAPD
0          ARREST_KEY           DR_NO
1         ARREST_DATE       Date Rptd
2               PD_CD        DATE OCC
3             PD_DESC        TIME OCC
4               KY_CD            AREA
5           OFNS_DESC       AREA NAME
6            LAW_CODE     Rpt Dist No
7          LAW_CAT_CD        Part 1-2
8         ARREST_BORO          Crm Cd
9     ARREST_PRECINCT     Crm Cd Desc
10  JURISDICTION_CODE         Mocodes
11          AGE_GROUP        Vict Age
12           PERP_SEX        Vict Sex
13          PERP_RACE    Vict Descent
14         X_COORD_CD       Premis Cd
15         Y_COORD_CD     Premis Desc
16           Latitude  Weapon Used Cd
17          Longitude     Weapon Desc
18            Lon_Lat          Status
19                NaN     Status Desc
20                NaN        Crm Cd 1
21                NaN        Crm Cd 2
22                NaN        Crm Cd 3
23                NaN        Crm Cd 4
24                NaN        LOCATION
25                NaN    Cross Street
26                NaN             LAT
27                NaN             LON

# missing values bekijken

In [61]:
missing_nypd = (
    df_nypd.isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

missing_lapd = (
    df_lapd.isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)
print(missing_nypd)
print(missing_lapd)

LAW_CAT_CD           0.718480
KY_CD                0.062483
PD_CD                0.049779
OFNS_DESC            0.011186
PD_DESC              0.011186
Lon_Lat              0.000320
Latitude             0.000320
Longitude            0.000320
ARREST_KEY           0.000000
ARREST_DATE          0.000000
LAW_CODE             0.000000
JURISDICTION_CODE    0.000000
ARREST_PRECINCT      0.000000
ARREST_BORO          0.000000
AGE_GROUP            0.000000
X_COORD_CD           0.000000
PERP_RACE            0.000000
PERP_SEX             0.000000
Y_COORD_CD           0.000000
dtype: float64
Crm Cd 4          99.993631
Crm Cd 3          99.769727
Crm Cd 2          93.118279
Cross Street      84.652312
Weapon Used Cd    67.437760
Weapon Desc       67.437760
Mocodes           15.085969
Vict Descent      14.393856
Vict Sex          14.392662
Premis Desc        0.058514
Premis Cd          0.001592
Crm Cd 1           0.001095
Status             0.000100
Vict Age           0.000000
Crm Cd             0.000000
Crm Cd Desc        0.000000
AREA NAME          0.000000
Rpt Dist No        0.000000
AREA               0.000000
TIME OCC           0.000000
Date Rptd          0.000000
DATE OCC           0.000000
DR_NO              0.000000
Part 1-2           0.000000
Status Desc        0.000000
LOCATION           0.000000
LAT                0.000000
LON                0.000000
dtype: float64

In [62]:
threshold = 0.5

df_nypd = df_nypd.loc[:, df_nypd.isna().mean() < threshold]

In [63]:
threshold = 0.5

df_lapd = df_lapd.loc[:, df_lapd.isna().mean() < threshold]

In [64]:
print(df_nypd.columns.tolist())
print(df_lapd.columns.tolist())

['ARREST_KEY', 'ARREST_DATE', 'PD_CD', 'PD_DESC', 'KY_CD', 'OFNS_DESC', 'LAW_CODE', 'LAW_CAT_CD', 'ARREST_BORO', 'ARREST_PRECINCT', 'JURISDICTION_CODE', 'AGE_GROUP', 'PERP_SEX', 'PERP_RACE', 'X_COORD_CD', 'Y_COORD_CD', 'Latitude', 'Longitude', 'Lon_Lat']
['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME', 'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes', 'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc', 'Status', 'Status Desc', 'Crm Cd 1', 'LOCATION', 'LAT', 'LON']

In [65]:
(df_nypd.isna().mean() * 100).sort_values(ascending=False)

LAW_CAT_CD           0.718480
KY_CD                0.062483
PD_CD                0.049779
OFNS_DESC            0.011186
PD_DESC              0.011186
Lon_Lat              0.000320
Latitude             0.000320
Longitude            0.000320
ARREST_KEY           0.000000
ARREST_DATE          0.000000
LAW_CODE             0.000000
JURISDICTION_CODE    0.000000
ARREST_PRECINCT      0.000000
ARREST_BORO          0.000000
AGE_GROUP            0.000000
X_COORD_CD           0.000000
PERP_RACE            0.000000
PERP_SEX             0.000000
Y_COORD_CD           0.000000
dtype: float64

In [66]:
(df_lapd.isna().mean() * 100).sort_values(ascending=False)

Mocodes         15.085969
Vict Descent    14.393856
Vict Sex        14.392662
Premis Desc      0.058514
Premis Cd        0.001592
Crm Cd 1         0.001095
Status           0.000100
AREA             0.000000
AREA NAME        0.000000
DATE OCC         0.000000
Date Rptd        0.000000
DR_NO            0.000000
TIME OCC         0.000000
Rpt Dist No      0.000000
Vict Age         0.000000
Part 1-2         0.000000
Crm Cd           0.000000
Crm Cd Desc      0.000000
Status Desc      0.000000
LOCATION         0.000000
LAT              0.000000
LON              0.000000
dtype: float64

## vorm van datum netjes gemaakt + kolommen jaar en maand toegevoegd

In [67]:
df_nypd["arrest_date"] = pd.to_datetime(df_nypd["ARREST_DATE"])

df_lapd["DATE OCC"] = pd.to_datetime(df_lapd["DATE OCC"])

C:\Users\lisah\AppData\Local\Temp\ipykernel_17596\2118804888.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_lapd["DATE OCC"] = pd.to_datetime(df_lapd["DATE OCC"])

In [68]:
df_nypd["ARREST_DATE"].head(10)

0    12/31/2025
1    12/31/2025
2    12/31/2025
3    12/31/2025
4    12/31/2025
5    12/31/2025
6    12/31/2025
7    12/31/2025
8    12/31/2025
9    12/31/2025
Name: ARREST_DATE, dtype: str

In [69]:
df_lapd["DATE OCC"].head(10)

0   2020-11-07
1   2020-10-18
2   2020-10-30
3   2020-12-24
4   2020-09-29
5   2020-11-11
6   2020-04-16
7   2020-07-07
8   2020-03-02
9   2020-09-01
Name: DATE OCC, dtype: datetime64[us]

In [70]:
print(df_nypd["ARREST_DATE"].dropna().iloc[:10].tolist())
print(df_lapd["DATE OCC"].dropna().iloc[:10].tolist())

['12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025', '12/31/2025']
[Timestamp('2020-11-07 00:00:00'), Timestamp('2020-10-18 00:00:00'), Timestamp('2020-10-30 00:00:00'), Timestamp('2020-12-24 00:00:00'), Timestamp('2020-09-29 00:00:00'), Timestamp('2020-11-11 00:00:00'), Timestamp('2020-04-16 00:00:00'), Timestamp('2020-07-07 00:00:00'), Timestamp('2020-03-02 00:00:00'), Timestamp('2020-09-01 00:00:00')]

In [71]:
df_nypd["ARREST_DATE"] = pd.to_datetime(
    df_nypd["ARREST_DATE"],
    format="%m/%d/%Y"
)

In [72]:
df_nypd["ARREST_DATE"].dtype

dtype('<M8[us]')

In [73]:
df_lapd["DATE OCC"].dtype

dtype('<M8[us]')

In [74]:
df_nypd["year"] = df_nypd["ARREST_DATE"].dt.year
df_nypd["month"] = df_nypd["ARREST_DATE"].dt.month

df_lapd["year"] = df_lapd["DATE OCC"].dt.year
df_lapd["month"] = df_lapd["DATE OCC"].dt.month

In [75]:
df_nypd = df_nypd[
    (df_nypd['ARREST_DATE'].dt.year >= 2020) & 
    (df_nypd['ARREST_DATE'].dt.year <= 2023)
]
print(f"NYPD gefilterd: {len(df_nypd)} rijen")

NYPD gefilterd: 712075 rijen

In [76]:
df_lapd = df_lapd[
    (df_lapd['DATE OCC'].dt.year >= 2020) & 
    (df_lapd['DATE OCC'].dt.year <= 2023)
]

print(f"LAPD gefilterd: {len(df_lapd)} rijen")

LAPD gefilterd: 877327 rijen

In [77]:
df_nypd = df_nypd[[
    'ARREST_DATE',
    'OFNS_DESC',
    'LAW_CAT_CD',
    'ARREST_BORO',
    'AGE_GROUP',
    'PERP_SEX',
    'PERP_RACE',
    'Latitude',
    'Longitude',
    'year',
    'month'
]]

df_lapd = df_lapd[[
    'DATE OCC',
    'Crm Cd Desc',
    'Part 1-2',
    'AREA NAME',
    'Vict Age',
    'Vict Sex',
    'Vict Descent',
    'LAT',
    'LON',
    'year',
    'month'
]]

print(df_nypd.shape)
print(df_lapd.shape)

(712075, 11)
(877327, 11)

## Visualisaties

In [78]:


nypd_per_jaar = df_nypd.groupby('year').size().reset_index(name='count')
nypd_per_jaar['city'] = 'NYC (NYPD)'

lapd_per_jaar = df_lapd.groupby('year').size().reset_index(name='count')
lapd_per_jaar['city'] = 'LA (LAPD)'

df_combined = pd.concat([nypd_per_jaar, lapd_per_jaar])

jaren = [2020, 2021, 2022, 2023]

nypd_vals = nypd_per_jaar.set_index('year').reindex(jaren)['count']
lapd_vals = lapd_per_jaar.set_index('year').reindex(jaren)['count']

fig = go.Figure()

fig.add_trace(go.Bar(
    x=jaren,
    y=nypd_vals,
    name='NYC (NYPD)',
    marker_color='#1f77b4',
    text=[f'{int(v):,}' for v in nypd_vals],
    textposition='outside'
))

fig.add_trace(go.Bar(
    x=jaren,
    y=lapd_vals,
    name='LA (LAPD)',
    marker_color='#ff7f0e',
    text=[f'{int(v):,}' for v in lapd_vals],
    textposition='outside'
))

fig.update_layout(
    barmode='group',
    title=dict(text='Misdaden per jaar: NYC vs LA (2020–2024)', font=dict(size=20, family='Arial Black')),
    xaxis_title='Jaar',
    yaxis_title='Aantal misdaden / arrestaties',
    xaxis=dict(tickmode='array', tickvals=jaren),
    yaxis=dict(tickformat=','),
    legend=dict(title=''),
    template='plotly_white',
    width=900,
    height=600
)

fig.write_image('misdaden_per_jaar_nyc_vs_la.png', scale=2)
fig.show()

In [79]:


df_nypd['year_month'] = df_nypd['ARREST_DATE'].dt.to_period('M')
df_lapd['year_month'] = df_lapd['DATE OCC'].dt.to_period('M')

nypd_maand = df_nypd.groupby('year_month').size().reset_index(name='count')
lapd_maand = df_lapd.groupby('year_month').size().reset_index(name='count')

nypd_maand['year_month'] = nypd_maand['year_month'].dt.to_timestamp()
lapd_maand['year_month'] = lapd_maand['year_month'].dt.to_timestamp()

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=nypd_maand['year_month'],
    y=nypd_maand['count'],
    mode='lines',
    name='NYC (NYPD)',
    line=dict(color='#1f77b4', width=2)
))

fig.add_trace(go.Scatter(
    x=lapd_maand['year_month'],
    y=lapd_maand['count'],
    mode='lines',
    name='LA (LAPD)',
    line=dict(color='#ff7f0e', width=2)
))

fig.update_layout(
    title=dict(text='Misdaden per maand: NYC vs LA (2020–2023)', font=dict(size=20, family='Arial Black')),
    xaxis_title='Periode',
    yaxis_title='Aantal misdaden / arrestaties',
    xaxis=dict(
        tickmode='array',
        tickvals=pd.date_range('2020-01-01', '2024-01-01', freq='YS'),
        ticktext=[str(y) for y in range(2020, 2025)]
    ),
    yaxis=dict(tickformat=','),
    legend=dict(title=''),
    template='plotly_white',
    width=1100,
    height=500
)

fig.write_image('misdaden_per_maand_nyc_vs_la.png', scale=2)
fig.show()

In [80]:


nypd_types = (df_nypd['OFNS_DESC']
              .value_counts()
              .head(10)
              .reset_index())
nypd_types.columns = ['misdaad', 'count']

lapd_types = (df_lapd['Crm Cd Desc']
              .value_counts()
              .head(10)
              .reset_index())
lapd_types.columns = ['misdaad', 'count']

fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=('Top 10 misdaden — NYC (NYPD)', 'Top 10 misdaden — LA (LAPD)')
)

fig.add_trace(go.Bar(
    x=nypd_types['count'][::-1],
    y=nypd_types['misdaad'][::-1],
    orientation='h',
    marker_color='#1f77b4',
    text=[f'{int(v):,}' for v in nypd_types['count'][::-1]],
    textposition='outside',
    name='NYC (NYPD)'
), row=1, col=1)

fig.add_trace(go.Bar(
    x=lapd_types['count'][::-1],
    y=lapd_types['misdaad'][::-1],
    orientation='h',
    marker_color='#ff7f0e',
    text=[f'{int(v):,}' for v in lapd_types['count'][::-1]],
    textposition='outside',
    name='LA (LAPD)'
), row=1, col=2)

fig.update_xaxes(title_text='Aantal arrestaties', tickformat=',', row=1, col=1)
fig.update_xaxes(title_text='Aantal meldingen', tickformat=',', row=1, col=2)

fig.update_layout(
    showlegend=False,
    template='plotly_white',
    width=1400,
    height=700,
    title=dict(font=dict(size=20, family='Arial Black'))
)

fig.write_image('misdaadtypes_nyc_vs_la.png', scale=2)
fig.show()

In [81]:
nyc_borough_coords = {
    'MANHATTAN': {'lat': 40.7831, 'lon': -73.9712},
    'BRONX': {'lat': 40.8448, 'lon': -73.8648},
    'BROOKLYN': {'lat': 40.6782, 'lon': -73.9442},
    'QUEENS': {'lat': 40.7282, 'lon': -73.7949},
    'STATEN ISLAND': {'lat': 40.5795, 'lon': -74.1502}
}

# NYPD gebruikt vaak afkortingen: K, Q, M, B, S
nyc_borough_map = {
    'K': 'BROOKLYN', 'Q': 'QUEENS', 'M': 'MANHATTAN', 
    'B': 'BRONX', 'S': 'STATEN ISLAND'
}
df_nypd['borough_naam'] = df_nypd['ARREST_BORO'].map(nyc_borough_map).fillna(df_nypd['ARREST_BORO'])

nypd_coords = pd.DataFrame([
    {'borough_naam': naam, 'Latitude': info['lat'], 'Longitude': info['lon']}
    for naam, info in nyc_borough_coords.items()
])

In [82]:
la_area_coords = {
    'Central': {'lat': 34.0445, 'lon': -118.2460},
    'Rampart': {'lat': 34.0586, 'lon': -118.2823},
    'Southwest': {'lat': 34.0141, 'lon': -118.3220},
    'Hollenbeck': {'lat': 34.0392, 'lon': -118.2080},
    'Harbor': {'lat': 33.7570, 'lon': -118.2920},
    'Hollywood': {'lat': 34.0980, 'lon': -118.3267},
    'Wilshire': {'lat': 34.0593, 'lon': -118.3470},
    'West LA': {'lat': 34.0461, 'lon': -118.4500},
    'Van Nuys': {'lat': 34.1870, 'lon': -118.4480},
    'West Valley': {'lat': 34.1900, 'lon': -118.5290},
    'Northeast': {'lat': 34.1062, 'lon': -118.2280},
    '77th Street': {'lat': 33.9700, 'lon': -118.2890},
    'Newton': {'lat': 34.0090, 'lon': -118.2540},
    'Pacific': {'lat': 33.9930, 'lon': -118.4280},
    'N Hollywood': {'lat': 34.1870, 'lon': -118.3790},
    'Foothill': {'lat': 34.2570, 'lon': -118.3700},
    'Devonshire': {'lat': 34.2520, 'lon': -118.5350},
    'Southeast': {'lat': 33.9380, 'lon': -118.2480},
    'Mission': {'lat': 34.2720, 'lon': -118.4490},
    'Olympic': {'lat': 34.0610, 'lon': -118.3050},
    'Topanga': {'lat': 34.1980, 'lon': -118.6050}
}

lapd_coords = pd.DataFrame([
    {'AREA NAME': naam, 'LAT': info['lat'], 'LON': info['lon']}
    for naam, info in la_area_coords.items()
])

In [83]:
# --- Top 5 + overig per stad bepalen ---
def top5_plus_overig(df, col):
    top5 = df[col].value_counts().head(5).index.tolist()
    return df[col].apply(lambda x: x if x in top5 else 'Overig')

df_nypd['categorie'] = top5_plus_overig(df_nypd, 'OFNS_DESC')
df_lapd['categorie'] = top5_plus_overig(df_lapd, 'Crm Cd Desc')



# Vaste kleuren per categorie zodat alle pies dezelfde legenda gebruiken
alle_categorieen = sorted(set(df_nypd['categorie'].unique()) | {'Overig'})
kleuren_nypd = px.colors.qualitative.Set3
categorie_kleuren_nypd = {cat: kleuren_nypd[i % len(kleuren_nypd)] 
                          for i, cat in enumerate(sorted(df_nypd['categorie'].unique()))}
categorie_kleuren_lapd = {cat: kleuren_nypd[i % len(kleuren_nypd)] 
                           for i, cat in enumerate(sorted(df_lapd['categorie'].unique()))}

In [84]:
print(df_nypd['ARREST_BORO'].unique())
print(df_lapd['AREA NAME'].unique())

<StringArray>
['M', 'B', 'K', 'Q', 'S']
Length: 5, dtype: str
<StringArray>
['N Hollywood',    'Van Nuys',    'Wilshire',     'Pacific',  'Hollenbeck',
   'Southwest',   'Northeast',  'Devonshire',     'Topanga',   'Hollywood',
     'Olympic',   'Southeast',      'Newton',    'Foothill',     'Mission',
     'Rampart',     'Central',     'West LA', '77th Street', 'West Valley',
      'Harbor']
Length: 21, dtype: str

In [85]:
# NYC mapping toepassen
nyc_borough_map = {
    'K': 'BROOKLYN', 'Q': 'QUEENS', 'M': 'MANHATTAN', 
    'B': 'BRONX', 'S': 'STATEN ISLAND'
}
df_nypd['borough_naam'] = df_nypd['ARREST_BORO'].map(nyc_borough_map)

# Check of alles gemapt is (geen NaN)
print(df_nypd['borough_naam'].isna().sum())  # moet 0 zijn

0

In [86]:
print(set(df_lapd['AREA NAME'].unique()) - set(la_area_coords.keys()))  # moet leeg zijn: set()

set()

In [87]:
# Pie-data per wijk per categorie
nypd_pie_data = df_nypd.groupby(['borough_naam', 'categorie']).size().reset_index(name='count')
lapd_pie_data = df_lapd.groupby(['AREA NAME', 'categorie']).size().reset_index(name='count')

In [88]:
# --- Top 5 + overig per stad bepalen ---
def top5_plus_overig(df, col):
    top5 = df[col].value_counts().head(5).index.tolist()
    return df[col].apply(lambda x: x if x in top5 else 'Overig')

df_nypd['categorie'] = top5_plus_overig(df_nypd, 'OFNS_DESC')
df_lapd['categorie'] = top5_plus_overig(df_lapd, 'Crm Cd Desc')


# Vaste kleuren per categorie zodat alle pies dezelfde legenda gebruiken
alle_categorieen = sorted(set(df_nypd['categorie'].unique()) | {'Overig'})
kleuren_nypd = px.colors.qualitative.Set3
categorie_kleuren_nypd = {cat: kleuren_nypd[i % len(kleuren_nypd)] 
                          for i, cat in enumerate(sorted(df_nypd['categorie'].unique()))}
categorie_kleuren_lapd = {cat: kleuren_nypd[i % len(kleuren_nypd)] 
                           for i, cat in enumerate(sorted(df_lapd['categorie'].unique()))}

In [90]:

def maak_donut_grid_kaart(pie_data, coords, wijk_col, kleuren_dict, titel, cols=3):
    wijken = coords[wijk_col].tolist()
    n_wijken = len(wijken)
    rows = int(np.ceil(n_wijken / cols))
    
    specs = [[{'type': 'domain'} for _ in range(cols)] for _ in range(rows)]
    fig = make_subplots(rows=rows, cols=cols, specs=specs,
                         subplot_titles=wijken)
    
    for i, wijk in enumerate(wijken):
        row = i // cols + 1
        col = i % cols + 1
        wijk_data = pie_data[pie_data[wijk_col] == wijk]
        
        fig.add_trace(go.Pie(
            labels=wijk_data['categorie'],
            values=wijk_data['count'],
            hole=0.4,
            name=wijk,
            marker=dict(colors=[kleuren_dict.get(c, '#cccccc') for c in wijk_data['categorie']]),
            showlegend=(i == 0)  # legenda alleen bij de eerste, voorkomt duplicaten
        ), row=row, col=col)
    
    fig.update_layout(title=titel, height=320*rows, showlegend=True)
    return fig

# NYC
fig_nyc_c = maak_donut_grid_kaart(
    nypd_pie_data, nypd_coords, 'borough_naam', 
    categorie_kleuren_nypd, 'NYC — Misdaadcategorieën per Borough'
)
fig_nyc_c.show()

# LA
fig_la_c = maak_donut_grid_kaart(
    lapd_pie_data, lapd_coords, 'AREA NAME', 
    categorie_kleuren_lapd, 'LA — Misdaadcategorieën per Area'
)
fig_la_c.show()

In [93]:


def maak_donut_grid_kaart(pie_data, coords, wijk_col, kleuren_dict, titel, cols=3):
    wijken = coords[wijk_col].tolist()
    n_wijken = len(wijken)
    rows = int(np.ceil(n_wijken / cols))
    
    specs = [[{'type': 'domain'} for _ in range(cols)] for _ in range(rows)]
    fig = make_subplots(
        rows=rows, cols=cols, specs=specs,
        subplot_titles=wijken,
        horizontal_spacing=0.05,
        vertical_spacing=0.15
    )
    
    for i, wijk in enumerate(wijken):
        row = i // cols + 1
        col = i % cols + 1
        wijk_data = pie_data[pie_data[wijk_col] == wijk]
        
        fig.add_trace(go.Pie(
            labels=wijk_data['categorie'],
            values=wijk_data['count'],
            hole=0.4,
            name=wijk,
            marker=dict(colors=[kleuren_dict.get(c, '#cccccc') for c in wijk_data['categorie']]),
            showlegend=(i == 0),
            textposition='inside',
            textinfo='percent'
        ), row=row, col=col)
    
    fig.update_layout(
        title=titel,
        height=400*rows,
        width=350*cols,
        showlegend=True
    )
    return fig

fig_nyc_c = maak_donut_grid_kaart(
    nypd_pie_data, nypd_coords, 'borough_naam', 
    categorie_kleuren_nypd, 'NYC — Misdaadcategorieën per Borough', cols=3
)
fig_nyc_c.show()

fig_la_c = maak_donut_grid_kaart(
    lapd_pie_data, lapd_coords, 'AREA NAME', 
    categorie_kleuren_lapd, 'LA — Misdaadcategorieën per Area', cols=5
)
fig_la_c.show()